# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from placementdriver import placementdriver_pb2 as placementdriver_dot_placementdriver__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in placementdriver/placementdriver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlacementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorker = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/GetWorker',
                request_serializer=placementdriver_dot_placementdriver__pb2.GetWorkerRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.GetWorkerResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/RegisterWorker',
                request_serializer=placementdriver_dot_placementdriver__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/Heartbeat',
                request_serializer=placementdriver_dot_placementdriver__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ListWorkers = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/ListWorkers',
                request_serializer=placementdriver_dot_placementdriver__pb2.ListWorkersRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.ListWorkersResponse.FromString,
                _registered_method=True)
        self.ListWorkersForCollection = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/ListWorkersForCollection',
                request_serializer=placementdriver_dot_placementdriver__pb2.ListWorkersForCollectionRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.ListWorkersForCollectionResponse.FromString,
                _registered_method=True)
        self.DrainWorker = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/DrainWorker',
                request_serializer=placementdriver_dot_placementdriver__pb2.DrainWorkerRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.DrainWorkerResponse.FromString,
                _registered_method=True)
        self.RemoveWorker = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/RemoveWorker',
                request_serializer=placementdriver_dot_placementdriver__pb2.RemoveWorkerRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.RemoveWorkerResponse.FromString,
                _registered_method=True)
        self.Rebalance = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/Rebalance',
                request_serializer=placementdriver_dot_placementdriver__pb2.RebalanceRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.RebalanceResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/CreateCollection',
                request_serializer=placementdriver_dot_placementdriver__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/ListCollections',
                request_serializer=placementdriver_dot_placementdriver__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/DeleteCollection',
                request_serializer=placementdriver_dot_placementdriver__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.DeleteCollectionResponse.FromString,
                _registered_method=True)
        self.GetCollectionStatus = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/GetCollectionStatus',
                request_serializer=placementdriver_dot_placementdriver__pb2.GetCollectionStatusRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.GetCollectionStatusResponse.FromString,
                _registered_method=True)
        self.GetLeader = channel.unary_unary(
                '/vectron.placementdriver.v1.PlacementService/GetLeader',
                request_serializer=placementdriver_dot_placementdriver__pb2.GetLeaderRequest.SerializeToString,
                response_deserializer=placementdriver_dot_placementdriver__pb2.GetLeaderResponse.FromString,
                _registered_method=True)


class PlacementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWorker(self, request, context):
        """Get worker address for a collection + optional vector ID (for consistent hashing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Worker registers itself on startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker sends heartbeat (every 5s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkers(self, request, context):
        """List all workers (for monitoring)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkersForCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainWorker(self, request, context):
        """Admin: drain a worker (move shards away, stop new assignments)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWorker(self, request, context):
        """Admin: remove a worker (only when it has no shards)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rebalance(self, request, context):
        """Admin: force rebalance (future)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Collection management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlacementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorker,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.GetWorkerRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.GetWorkerResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.HeartbeatRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.ListWorkersRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.ListWorkersResponse.SerializeToString,
            ),
            'ListWorkersForCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkersForCollection,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.ListWorkersForCollectionRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.ListWorkersForCollectionResponse.SerializeToString,
            ),
            'DrainWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainWorker,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.DrainWorkerRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.DrainWorkerResponse.SerializeToString,
            ),
            'RemoveWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWorker,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.RemoveWorkerRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.RemoveWorkerResponse.SerializeToString,
            ),
            'Rebalance': grpc.unary_unary_rpc_method_handler(
                    servicer.Rebalance,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.RebalanceRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.RebalanceResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.CreateCollectionRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.ListCollectionsRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.DeleteCollectionResponse.SerializeToString,
            ),
            'GetCollectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionStatus,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.GetCollectionStatusRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.GetCollectionStatusResponse.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=placementdriver_dot_placementdriver__pb2.GetLeaderRequest.FromString,
                    response_serializer=placementdriver_dot_placementdriver__pb2.GetLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectron.placementdriver.v1.PlacementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectron.placementdriver.v1.PlacementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlacementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/GetWorker',
            placementdriver_dot_placementdriver__pb2.GetWorkerRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.GetWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/RegisterWorker',
            placementdriver_dot_placementdriver__pb2.RegisterWorkerRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/Heartbeat',
            placementdriver_dot_placementdriver__pb2.HeartbeatRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/ListWorkers',
            placementdriver_dot_placementdriver__pb2.ListWorkersRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.ListWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkersForCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/ListWorkersForCollection',
            placementdriver_dot_placementdriver__pb2.ListWorkersForCollectionRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.ListWorkersForCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/DrainWorker',
            placementdriver_dot_placementdriver__pb2.DrainWorkerRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.DrainWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/RemoveWorker',
            placementdriver_dot_placementdriver__pb2.RemoveWorkerRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.RemoveWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rebalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/Rebalance',
            placementdriver_dot_placementdriver__pb2.RebalanceRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.RebalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/CreateCollection',
            placementdriver_dot_placementdriver__pb2.CreateCollectionRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/ListCollections',
            placementdriver_dot_placementdriver__pb2.ListCollectionsRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/DeleteCollection',
            placementdriver_dot_placementdriver__pb2.DeleteCollectionRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.DeleteCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/GetCollectionStatus',
            placementdriver_dot_placementdriver__pb2.GetCollectionStatusRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.GetCollectionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.placementdriver.v1.PlacementService/GetLeader',
            placementdriver_dot_placementdriver__pb2.GetLeaderRequest.SerializeToString,
            placementdriver_dot_placementdriver__pb2.GetLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
