# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apigateway import apigateway_pb2 as apigateway_dot_apigateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in apigateway/apigateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectronServiceStub(object):
    """===============================================
    Vectron Public API — The ONE users see
    ===============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/vectron.v1.VectronService/CreateCollection',
                request_serializer=apigateway_dot_apigateway__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.Upsert = channel.unary_unary(
                '/vectron.v1.VectronService/Upsert',
                request_serializer=apigateway_dot_apigateway__pb2.UpsertRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/vectron.v1.VectronService/Search',
                request_serializer=apigateway_dot_apigateway__pb2.SearchRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/vectron.v1.VectronService/Get',
                request_serializer=apigateway_dot_apigateway__pb2.GetRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/vectron.v1.VectronService/Delete',
                request_serializer=apigateway_dot_apigateway__pb2.DeleteRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/vectron.v1.VectronService/ListCollections',
                request_serializer=apigateway_dot_apigateway__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.GetCollectionStatus = channel.unary_unary(
                '/vectron.v1.VectronService/GetCollectionStatus',
                request_serializer=apigateway_dot_apigateway__pb2.GetCollectionStatusRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.GetCollectionStatusResponse.FromString,
                _registered_method=True)
        self.UpdateUserProfile = channel.unary_unary(
                '/vectron.v1.VectronService/UpdateUserProfile',
                request_serializer=apigateway_dot_apigateway__pb2.UpdateUserProfileRequest.SerializeToString,
                response_deserializer=apigateway_dot_apigateway__pb2.UpdateUserProfileResponse.FromString,
                _registered_method=True)


class VectronServiceServicer(object):
    """===============================================
    Vectron Public API — The ONE users see
    ===============================================

    """

    def CreateCollection(self, request, context):
        """Create a new collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upsert(self, request, context):
        """Upsert vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get point by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete point by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """List all collections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionStatus(self, request, context):
        """Get collection status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """Update user profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectronServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=apigateway_dot_apigateway__pb2.CreateCollectionRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=apigateway_dot_apigateway__pb2.UpsertRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.UpsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=apigateway_dot_apigateway__pb2.SearchRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.SearchResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=apigateway_dot_apigateway__pb2.GetRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=apigateway_dot_apigateway__pb2.DeleteRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=apigateway_dot_apigateway__pb2.ListCollectionsRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'GetCollectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionStatus,
                    request_deserializer=apigateway_dot_apigateway__pb2.GetCollectionStatusRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.GetCollectionStatusResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=apigateway_dot_apigateway__pb2.UpdateUserProfileRequest.FromString,
                    response_serializer=apigateway_dot_apigateway__pb2.UpdateUserProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectron.v1.VectronService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectron.v1.VectronService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectronService(object):
    """===============================================
    Vectron Public API — The ONE users see
    ===============================================

    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/CreateCollection',
            apigateway_dot_apigateway__pb2.CreateCollectionRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/Upsert',
            apigateway_dot_apigateway__pb2.UpsertRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/Search',
            apigateway_dot_apigateway__pb2.SearchRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/Get',
            apigateway_dot_apigateway__pb2.GetRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/Delete',
            apigateway_dot_apigateway__pb2.DeleteRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/ListCollections',
            apigateway_dot_apigateway__pb2.ListCollectionsRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/GetCollectionStatus',
            apigateway_dot_apigateway__pb2.GetCollectionStatusRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.GetCollectionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.v1.VectronService/UpdateUserProfile',
            apigateway_dot_apigateway__pb2.UpdateUserProfileRequest.SerializeToString,
            apigateway_dot_apigateway__pb2.UpdateUserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
