# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from auth import auth_pb2 as auth_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """================== Service Definition ==================

    AuthService provides user account and API key management.
    --- User Account Management ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/vectron.auth.v1.AuthService/RegisterUser',
                request_serializer=auth_dot_auth__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.RegisterUserResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/vectron.auth.v1.AuthService/Login',
                request_serializer=auth_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetUserProfile = channel.unary_unary(
                '/vectron.auth.v1.AuthService/GetUserProfile',
                request_serializer=auth_dot_auth__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.GetUserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateUserProfile = channel.unary_unary(
                '/vectron.auth.v1.AuthService/UpdateUserProfile',
                request_serializer=auth_dot_auth__pb2.UpdateUserProfileRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.UpdateUserProfileResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/vectron.auth.v1.AuthService/DeleteUser',
                request_serializer=auth_dot_auth__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/vectron.auth.v1.AuthService/RefreshToken',
                request_serializer=auth_dot_auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.CreateAPIKey = channel.unary_unary(
                '/vectron.auth.v1.AuthService/CreateAPIKey',
                request_serializer=auth_dot_auth__pb2.CreateAPIKeyRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.CreateAPIKeyResponse.FromString,
                _registered_method=True)
        self.ListAPIKeys = channel.unary_unary(
                '/vectron.auth.v1.AuthService/ListAPIKeys',
                request_serializer=auth_dot_auth__pb2.ListAPIKeysRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.ListAPIKeysResponse.FromString,
                _registered_method=True)
        self.DeleteAPIKey = channel.unary_unary(
                '/vectron.auth.v1.AuthService/DeleteAPIKey',
                request_serializer=auth_dot_auth__pb2.DeleteAPIKeyRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.DeleteAPIKeyResponse.FromString,
                _registered_method=True)
        self.ValidateAPIKey = channel.unary_unary(
                '/vectron.auth.v1.AuthService/ValidateAPIKey',
                request_serializer=auth_dot_auth__pb2.ValidateAPIKeyRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.ValidateAPIKeyResponse.FromString,
                _registered_method=True)
        self.CreateSDKJWT = channel.unary_unary(
                '/vectron.auth.v1.AuthService/CreateSDKJWT',
                request_serializer=auth_dot_auth__pb2.CreateSDKJWTRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.CreateSDKJWTResponse.FromString,
                _registered_method=True)
        self.GetAuthDetailsForSDK = channel.unary_unary(
                '/vectron.auth.v1.AuthService/GetAuthDetailsForSDK',
                request_serializer=auth_dot_auth__pb2.GetAuthDetailsForSDKRequest.SerializeToString,
                response_deserializer=auth_dot_auth__pb2.GetAuthDetailsForSDKResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """================== Service Definition ==================

    AuthService provides user account and API key management.
    --- User Account Management ---
    """

    def RegisterUser(self, request, context):
        """Register a new user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login a user and get a session JWT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """Get the current user's profile (requires JWT authentication).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """Update the current user's profile (requires JWT authentication).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Delete the current user's account (requires JWT authentication and optional password confirmation).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Refresh the current user's JWT token (requires valid JWT).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIKey(self, request, context):
        """--- API Key Management (requires JWT authentication) ---

        Create a new API key for the authenticated user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAPIKeys(self, request, context):
        """List all API keys for the authenticated user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAPIKey(self, request, context):
        """Delete an API key belonging to the authenticated user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAPIKey(self, request, context):
        """--- For Internal Services (e.g., API Gateway) ---

        Validate a raw API key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSDKJWT(self, request, context):
        """Create an SDK JWT for an existing API key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthDetailsForSDK(self, request, context):
        """Get user and plan details for a given API Key ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=auth_dot_auth__pb2.RegisterUserRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.RegisterUserResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=auth_dot_auth__pb2.GetUserProfileRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.GetUserProfileResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=auth_dot_auth__pb2.UpdateUserProfileRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.UpdateUserProfileResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=auth_dot_auth__pb2.DeleteUserRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.DeleteUserResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth_dot_auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'CreateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIKey,
                    request_deserializer=auth_dot_auth__pb2.CreateAPIKeyRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.CreateAPIKeyResponse.SerializeToString,
            ),
            'ListAPIKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAPIKeys,
                    request_deserializer=auth_dot_auth__pb2.ListAPIKeysRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.ListAPIKeysResponse.SerializeToString,
            ),
            'DeleteAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAPIKey,
                    request_deserializer=auth_dot_auth__pb2.DeleteAPIKeyRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.DeleteAPIKeyResponse.SerializeToString,
            ),
            'ValidateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAPIKey,
                    request_deserializer=auth_dot_auth__pb2.ValidateAPIKeyRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.ValidateAPIKeyResponse.SerializeToString,
            ),
            'CreateSDKJWT': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSDKJWT,
                    request_deserializer=auth_dot_auth__pb2.CreateSDKJWTRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.CreateSDKJWTResponse.SerializeToString,
            ),
            'GetAuthDetailsForSDK': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthDetailsForSDK,
                    request_deserializer=auth_dot_auth__pb2.GetAuthDetailsForSDKRequest.FromString,
                    response_serializer=auth_dot_auth__pb2.GetAuthDetailsForSDKResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectron.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectron.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """================== Service Definition ==================

    AuthService provides user account and API key management.
    --- User Account Management ---
    """

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/RegisterUser',
            auth_dot_auth__pb2.RegisterUserRequest.SerializeToString,
            auth_dot_auth__pb2.RegisterUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/Login',
            auth_dot_auth__pb2.LoginRequest.SerializeToString,
            auth_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/GetUserProfile',
            auth_dot_auth__pb2.GetUserProfileRequest.SerializeToString,
            auth_dot_auth__pb2.GetUserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/UpdateUserProfile',
            auth_dot_auth__pb2.UpdateUserProfileRequest.SerializeToString,
            auth_dot_auth__pb2.UpdateUserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/DeleteUser',
            auth_dot_auth__pb2.DeleteUserRequest.SerializeToString,
            auth_dot_auth__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/RefreshToken',
            auth_dot_auth__pb2.RefreshTokenRequest.SerializeToString,
            auth_dot_auth__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/CreateAPIKey',
            auth_dot_auth__pb2.CreateAPIKeyRequest.SerializeToString,
            auth_dot_auth__pb2.CreateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAPIKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/ListAPIKeys',
            auth_dot_auth__pb2.ListAPIKeysRequest.SerializeToString,
            auth_dot_auth__pb2.ListAPIKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/DeleteAPIKey',
            auth_dot_auth__pb2.DeleteAPIKeyRequest.SerializeToString,
            auth_dot_auth__pb2.DeleteAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/ValidateAPIKey',
            auth_dot_auth__pb2.ValidateAPIKeyRequest.SerializeToString,
            auth_dot_auth__pb2.ValidateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSDKJWT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/CreateSDKJWT',
            auth_dot_auth__pb2.CreateSDKJWTRequest.SerializeToString,
            auth_dot_auth__pb2.CreateSDKJWTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthDetailsForSDK(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectron.auth.v1.AuthService/GetAuthDetailsForSDK',
            auth_dot_auth__pb2.GetAuthDetailsForSDKRequest.SerializeToString,
            auth_dot_auth__pb2.GetAuthDetailsForSDKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
